
package org.cmu.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArticleQueryInterface", targetNamespace = "http://ws.cmu.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ArticleQueryInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.cmu.org/ArticleQueryInterface/selectAllArticleTitlesRequest", output = "http://ws.cmu.org/ArticleQueryInterface/selectAllArticleTitlesResponse")
    public String selectAllArticleTitles();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.cmu.org/ArticleQueryInterface/selectAllAuthorsRequest", output = "http://ws.cmu.org/ArticleQueryInterface/selectAllAuthorsResponse")
    public String selectAllAuthors();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.cmu.org/ArticleQueryInterface/selectAllTheTitleOfFristArticleRequest", output = "http://ws.cmu.org/ArticleQueryInterface/selectAllTheTitleOfFristArticleResponse")
    public String selectAllTheTitleOfFristArticle();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.cmu.org/ArticleQueryInterface/selectArticlesLaterThanRequest", output = "http://ws.cmu.org/ArticleQueryInterface/selectArticlesLaterThanResponse")
    public String selectArticlesLaterThan(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.cmu.org/ArticleQueryInterface/selectTitlesLaterThanRequest", output = "http://ws.cmu.org/ArticleQueryInterface/selectTitlesLaterThanResponse")
    public String selectTitlesLaterThan(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
